### ISSUE TITLE
少了一张图片

### ISSUE THREAD

**Issue by wujunze** [tuangauss/DataScienceProjects#1]
少了一张图片
![image](https://user-images.githubusercontent.com/12997869/44259830-3fb3ef00-a245-11e8-8330-8e47b2a1639b.png)

**Comment by Lancelothe** [comment]
同求

**Comment by tuangauss** [comment]
Hi, I have uploaded the jpg image that I used as requested.

For the record, I don't speak Mandarin so I would really appreciate if you could send requests in English  (Spanish, Vietnamese, or Korean could also work but let's keep it open for everyone)
