### ISSUE TITLE
New_Season

### ISSUE THREAD

**Issue by BetJayUK** [tuangauss/DataScienceProjects#3]
Hi, I'm just trying out your code and getting stuck on predictions.r.
I'm receiving 
`Error in mapply(get_score, new_season$HomeTeam, new_season$AwayTeam, nsim,  : 
  object 'new_season' not found`
error. Any ideas?

**Comment by tuangauss** [comment]
Hi, Thanks for raising the issue.

It turned out that the a bit of the code in `clean_data.R` was deleted, leading to the loss of the Global variable `new_season`, a dataframe that contains the 2018-19 fixtures. I have fixed the issue accordingly.
